### ISSUE TITLE
TypeError: Cannot read property 'kind' of null

### ISSUE THREAD

**Issue by hobbestherat** [sagifogel/typescript-closure-compiler#4]
/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:42929
            throw e;
            ^

TypeError: Cannot read property 'kind' of null
    at isAmbientVariableDeclaration (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39329:24)
    at getClassOrInterfaceFullPath (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39335:21)
    at /usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39365:60
    at emitIf (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39042:17)
    at emitAnnotationIf (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39052:13)
    at emitConstructorOrInterfaceAnnotation (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39347:13)
    at emitConstructorAnnotation (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39326:13)
    at emitConstructorWorker (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39421:17)
    at emitConstructor (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39394:13)
    at emitClassLikeDeclarationBelowES6 (/usr/local/lib/node_modules/typescript-closure-compiler/typescript.js:39909:13)

**Comment by sagifogel** [comment]
Please send me a minimal case that reproduces the problem.

**Comment by iamwhitebox** [comment]
@sagifogel try running `tscc` on any typescript file

**Comment by sagifogel** [comment]
@iamwhitebox tscc supports typecript 1.8. You are probably using a higher version of the typescript and therefore receive this error.
If you want me to make sure this is the case, you need to provide me with a minimum example.
